{
 "title": "Consensus",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   { "name": "role", "query": { "query": "label_values(role)" } },
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Committed blocks per sec",
   "type": "graph",
   "description": "The rate of the committed round number.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "blocks / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_last_committed_round{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Committed successful txns per sec",
   "type": "graph",
   "description": "The rate of the committed transaction version.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "transactions / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_last_committed_version{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latency breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Block creation to signed",
   "type": "graph",
   "description": "Duration between block generation time until the moment the leader signs it.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"signed\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"signed\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block creation to receive",
   "type": "graph",
   "description": "Duration between block generation time until the moment the node receives it in consensus.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"received\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"received\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block creation to synced",
   "type": "graph",
   "description": "Duration between block generation time until the moment the node is synced and ready to execute.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"synced\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"synced\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block creation to executed",
   "type": "graph",
   "description": "Duration between block generation time until the moment the node executes the block.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"executed\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"executed\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block creation to vote",
   "type": "graph",
   "description": "Duration between block generation time until the moment the node votes for it.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"voted\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"voted\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block creation to QC aggregated",
   "type": "graph",
   "description": "Duration between block generation time until the moment the QC is aggregated by leader.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"qc_aggregated\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"qc_aggregated\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block creation to QC received",
   "type": "graph",
   "description": "Duration between block generation time until the moment the node adds the QC.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"qc_added\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"qc_added\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block creation to commit",
   "type": "graph",
   "description": "Duration between block generation time until the moment the node commits it.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"committed\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"committed\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Main loop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Percent Time Event Loop Idle",
   "type": "graph",
   "description": "Percent of time the main Event Loop spends idle",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (rate(consensus_duration_sum{op='process_block_retrieval', job=~\"$job\"}[$interval]) + on (job) rate(consensus_duration_sum{op='process_message', job=~\"$job\"}[$interval]) + on (job) rate(consensus_duration_sum{op='process_local_timeout', job=~\"$job\"}[$interval])) / on(job) rate(consensus_duration_sum{op='main_loop', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Percent Time Event Loop process consensus msg",
   "type": "graph",
   "description": "Percent of time the main Event Loop spends for block retrieval",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_message', job=~\"$job\"}[$interval]) / on(job) rate(consensus_duration_sum{op='main_loop', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Percent Time Event Loop process block retrieval",
   "type": "graph",
   "description": "Percent of time the main Event Loop spends for block retrieval",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_block_retrieval', job=~\"$job\"}[$interval]) / on(job) rate(consensus_duration_sum{op='main_loop', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Percent Time process local timeout",
   "type": "graph",
   "description": "Percent of time the main loop spends for processing local timeout.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_local_timeout', job=~\"$job\"}[$interval]) / on(job) rate(consensus_duration_sum{op='main_loop', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Percent Time Process proposal",
   "type": "graph",
   "description": "Percent time spent in process proposal compared to all consensus msg",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_proposal', job=~\"$job\"}[$interval]) / on(job) rate(consensus_duration_sum{op='process_message',  job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Percent Time Process vote",
   "type": "graph",
   "description": "Percent time spent in process vote compared to all consensus msg",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_vote', job=~\"$job\"}[$interval]) / on(job) rate(consensus_duration_sum{op='process_message', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Percent Time Process sync info",
   "type": "graph",
   "description": "Percent time spent in process sync info compared to all consensus msg",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_sync_info', job=~\"$job\"}[$interval]) / on(job) rate(consensus_duration_sum{op='process_message', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Main Event Loop Error rate",
   "type": "graph",
   "description": "The error rate of main loop (timeout is considered as error)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_error_count{job=~\"$job\"}[$interval]) / on (job) rate(consensus_duration_count{op='main_loop', job=~\"$job\"}[$interval])",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Main Event Loop Current running function",
   "type": "graph",
   "description": "A sampled binary number indicating whether the node is currently in a function. (Useful when the node is stuck somewhere)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consensus_gauge{op='process_proposal_running', job=~\"$job\"}",
     "legendFormat": "{{job}}: proposal"
    },
    {
     "expr": "consensus_gauge{op='process_vote_running', job=~\"$job\"}",
     "legendFormat": "{{job}}: vote"
    },
    {
     "expr": "consensus_gauge{op='process_local_timeout_running', job=~\"$job\"}",
     "legendFormat": "{{job}}: timeout"
    },
    {
     "expr": "consensus_gauge{op='reconfig_running', job=~\"$job\"}",
     "legendFormat": "{{job}}: reconfig"
    },
    {
     "expr": "consensus_gauge{op='execute_block', job=~\"$job\"}",
     "legendFormat": "{{job}}: execute"
    },
    {
     "expr": "consensus_gauge{op='commit_block', job=~\"$job\"}",
     "legendFormat": "{{job}}: commit"
    },
    {
     "expr": "consensus_gauge{op='sync_to', job=~\"$job\"}",
     "legendFormat": "{{job}}: sync"
    },
    {
     "expr": "consensus_gauge{op='block_retrieval', job=~\"$job\"}",
     "legendFormat": "{{job}}: rpc"
    }
   ]
  },
  {
   "title": "RoundState",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true
  },
  {
   "title": "Current Round",
   "type": "graph",
   "description": "The current round consensus is at, the rate of this is roughly Committed blocks per sec.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "round #" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_current_round{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total QC rounds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "# rounds" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_qc_rounds_count{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total timeout rounds",
   "type": "graph",
   "description": "The total number of rounds that have timeout certificate.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "# timeout rounds" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_timeout_rounds_count{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total local timeout",
   "type": "graph",
   "description": "The total number a single node has timeout locally. When 2f+1 nodes have local timeout for the same round, a timeout round is formed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short", "label": "# timeouts" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_timeout_count{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Current Round timeout value",
   "type": "graph",
   "description": "The duration of a single round until it generates local timeout.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "ms", "label": "timeout val" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_round_timeout_s{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "EpochState",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true
  },
  {
   "title": "Current Epoch",
   "type": "graph",
   "description": "The current epoch number the node is in, the number is bumped with reconfiguration event like key rotation, validator set change etc.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Epoch #" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_epoch{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of validators",
   "type": "graph",
   "description": "Number of validators for the current epoch.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "# Validators" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_current_epoch_validators{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BlockStore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true
  },
  {
   "title": "Pending blocks",
   "type": "graph",
   "description": "Pending blocks in the block tree, typically it should be less than 3.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short", "label": "# blocks" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_num_blocks_in_tree{job=~\"$job\"} - 1",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "graph",
   "description": "The average number of transactions of a block, can impact the execution time and overall latency.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "yaxes": [
    { "format": "short", "label": "# transactions / block" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_num_txns_per_block_sum{job=~\"$job\"}[$interval]) / rate(diem_consensus_num_txns_per_block_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total wait duration",
   "type": "graph",
   "description": "Total time the node has to wait before inserting the block",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_wait_duration_s_sum{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "External call",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true
  },
  {
   "title": "Execute block Latency",
   "type": "graph",
   "description": "The average time to execute a block.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='execute_block', job=~\"$job\"}[$interval]) / rate(consensus_duration_count{op='execute_block', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Commit block Latency",
   "type": "graph",
   "description": "The average time to commit blocks (may commit more than 1 in a single call).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='commit_block', job=~\"$job\"}[$interval]) / rate(consensus_duration_count{op='commit_block',  job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Safety rules Latency",
   "type": "graph",
   "description": "The average latency of talking to safety rules (of all calls).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='safety_rules', job=~\"$job\"}[$interval]) / rate(consensus_duration_count{op='safety_rules', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pull txn Latency",
   "type": "graph",
   "description": "The average latency of pulling the txn from mempool.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='pull_txn', job=~\"$job\"}[$interval]) / rate(consensus_duration_count{op='pull_txn', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Notify mempool Latency",
   "type": "graph",
   "description": "The average latency of notifying mempool about failed transactions.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 103 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='notify_mempool', job=~\"$job\"}[$interval]) / rate(consensus_duration_count{op='notify_mempool', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Notify state sync Latency",
   "type": "graph",
   "description": "The average latency of notifying state sync of committed txn.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 103 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='notify_state_sync', job=~\"$job\"}[$interval]) / rate(consensus_duration_count{op='notify_state_sync', job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "State sync count",
   "type": "graph",
   "description": "The total count of call to sync to.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short", "label": "# state syncs" }
   ],
   "targets": [
    {
     "expr": "consensus_duration_count{op='sync_to', job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total time spent on state sync",
   "type": "graph",
   "description": "The total time spent in the external sync_to function.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "s", "label": "total time" }
   ],
   "targets": [
    {
     "expr": "consensus_duration_sum{op='sync_to', job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total sync Info Msgs sent to help peers",
   "type": "graph",
   "description": "The total number of sync info msg sent to help peers.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "short", "label": "# messages" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_sync_info_msg_sent_count{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block retrieval count",
   "type": "graph",
   "description": "The total number of block retrieval the node sends. It's required when the node is missing some ancestors of the block to be executed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short", "label": "# blocks" }
   ],
   "targets": [
    {
     "expr": "consensus_duration_count{op='block_retrieval', job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total time spent on block retrieval",
   "type": "graph",
   "description": "Total time spent in retrieval the blocks from peers. (This is blocking RPC call)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 119 },
   "yaxes": [
    { "format": "s", "label": "total time" }
   ],
   "targets": [
    {
     "expr": "consensus_duration_sum{op='block_retrieval', job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Proposer Election",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true
  },
  {
   "title": "Proposals rate",
   "type": "graph",
   "description": "The proposal rate of the node, indicating how many times it becomes leaders.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short", "label": "proposals / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_proposals_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total votes on Nil",
   "type": "graph",
   "description": "The total number the node votes on a NIL block when the round timeout. (when the proposer doesn't send proposal in time).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 128 },
   "yaxes": [
    { "format": "short", "label": "# votes" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_vote_nil_count{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Message queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "collapsed": true
  },
  {
   "title": "Network -> Consensus Pending Messages",
   "type": "graph",
   "description": "The channel metrics related to network layer to consensus.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_pending_network_events{state=\"enqueued\", job=~\"$job\"} - on (job) diem_consensus_pending_network_events{state=\"dequeued\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network -> Consensus Dropped Messages",
   "type": "graph",
   "description": "The channel metrics related to network layer to consensus.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 137 },
   "yaxes": [
    { "format": "short", "label": "dropped messages / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_pending_network_events{state=\"dropped\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Consensus -> Main loop (Block retrieval) Pending Messages",
   "type": "graph",
   "description": "The channel metrics related to consensus block retrieval (dedicated channel for the rpc).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_block_retrieval_channel_msgs_count{state=\"enqueued\", job=~\"$job\"} - on (job) diem_consensus_block_retrieval_channel_msgs_count{state=\"dequeued\", job=~\"$job\"}",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Consensus -> Main loop (Block retrieval) Dropped Messages",
   "type": "graph",
   "description": "The channel metrics related to consensus block retrieval (dedicated channel for the rpc).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 146 },
   "yaxes": [
    { "format": "short", "label": "messages dropped / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_block_retrieval_channel_msgs_count{state=\"dropped\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Consensus -> Main loop (Consensus Msg) Pending Messages",
   "type": "graph",
   "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_channel_msgs_count{state=\"enqueued\", job=~\"$job\"} - on (job) diem_consensus_channel_msgs_count{state=\"dequeued\", job=~\"$job\"} - on (job) diem_consensus_channel_msgs_count{state=\"dropped\", job=~\"$job\"}",
     "legendFormat": "{{owner}}-{{role}}"
    }
   ]
  },
  {
   "title": "Consensus -> Main loop (Consensus Msg) Dropped Messages",
   "type": "graph",
   "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 155 },
   "yaxes": [
    { "format": "short", "label": "dropped messages / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_consensus_channel_msgs_count{state=\"dropped\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pending self message",
   "type": "graph",
   "description": "The pending messages in the self message queue (for proposal and vote) and timeout queue (for local timeout).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_pending_self_messages{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pending round local timeouts",
   "type": "graph",
   "description": "The pending messages in the self message queue (for proposal and vote) and timeout queue (for local timeout).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_consensus_pending_round_timeouts{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}