{
 "title": "DDoS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network_id", "query": { "query": "label_values(network_id)" } },
   { "name": "role_type", "query": { "query": "label_values(role_type)" } },
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "rpc_protocol", "label": "RPC Protocol", "query": { "query": "label_values(protocol_id)" } },
   { "name": "AggInterval", "label": "Aggregation Interval", "query": "1m,5m,15m,30m,1h,3h,1d,7d" },
   { "name": "container", "query": { "query": "label_values(container)" } }
  ]
 },
 "panels": [
  { "title": "Inbound Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inbound Connected Peers",
   "type": "graph",
   "description": "Total Inbound connected peers.  There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id) (diem_connections{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", direction=\"inbound\"})",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Inbound Pending Connection Upgrades",
   "type": "graph",
   "description": "The rate of new inbound connections on the network interface",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id) (rate(diem_network_pending_connection_upgrades{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", direction=\"inbound\" }[$AggInterval]))",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Blocked Inbound Connections Rate (Connection Limit)",
   "type": "graph",
   "description": "Rate of connections being blocked by connection limits",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_connections_rejected{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", direction=\"inbound\"}[$AggInterval])",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Throughput of Total Inbound RPCs (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Inbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id)(rate(diem_network_rpc_bytes{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Inbound RPCs (msg/s)",
   "type": "graph",
   "description": "Total number of all Inbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id)(rate(diem_network_rpc_messages{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", type=\"request\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Throughput of Total Inbound Direct Sends (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Inbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id)(rate(diem_network_direct_send_bytes{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Inbound Direct Sends (msg/s)",
   "type": "graph",
   "description": "Total number of all Inbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id)(rate(diem_network_direct_send_messages{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "VFN Public Inbound Allowed bytes (bytes/s)",
   "type": "graph",
   "description": "number of bytes allowed through the throttler inbound per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    { "expr": "diem_network_rate_limit_sum", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "VFN Public Inbound Rate Limiting (bytes/s)",
   "type": "graph",
   "description": "number of bytes throttled inbound per second including partial messages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_network_rate_limit_sum{metric=\"throttled\", direction=\"inbound\", job=~\"$job\"}[$AggInterval])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}