{
 "title": "JSON-RPC",
 "description": "JSON-RPC service provides APIs for client applications to submit transactions and query the diem blockchain.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "requesttype", "label": "RequestType", "query": "single,batch" },
   {
    "name": "method",
    "label": "JSON-RPC Method",
    "query": "submit, get_account, get_account_transaction, get_account_transactions, get_transactions, get_events, get_metadata, get_currencies, get_state_proof, get_account_state_with_proof"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "role", "label": "Role", "query": { "query": "label_values(role)" } },
   { "name": "owner", "label": "Owner", "query": { "query": "label_values(owner)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JSON-RPC Throughput",
   "type": "graph",
   "description": "RPC endpoint level request count.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "requests / s" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(rate(diem_client_service_rpc_requests_count{type=~\"$requesttype\", job=~\"$job\"} [$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "JSON-RPC Request $requesttype Latency [P50]",
   "type": "graph",
   "description": "This latency is recorded at JSON-RPC handler level without knowing what method is called. There are 2 types, batch and single requests.  \nBatch request is total time for all methods call finished.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "repeat": "requesttype",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(diem_client_service_rpc_request_latency_seconds_bucket{job=~\"$job\"}[$interval])) by (job, type, le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Request $requesttype Latency [P90]",
   "type": "graph",
   "description": "This latency is recorded at JSON-RPC handler level without knowing what method is called. There are 2 types, batch and single requests.  \nBatch request is total time for all methods call finished.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "repeat": "requesttype",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(diem_client_service_rpc_request_latency_seconds_bucket{job=~\"$job\"}[$interval])) by (job, type, le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Request $requesttype Latency [P99]",
   "type": "graph",
   "description": "This latency is recorded at JSON-RPC handler level without knowing what method is called. There are 2 types, batch and single requests.  \nBatch request is total time for all methods call finished.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "repeat": "requesttype",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(diem_client_service_rpc_request_latency_seconds_bucket{job=~\"$job\"}[$interval])) by (job, type, le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "JSON-RPC Method Success",
   "type": "graph",
   "description": "The success rate of each json-rpc method",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "successes / s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, method) (rate(diem_client_service_requests_count{type=~\"$requesttype\", method=~\"$method\", result=\"success\", job=~\"$job\"} [$interval]))",
     "legendFormat": "{{job}}-{{method}}"
    }
   ]
  },
  {
   "title": "JSON-RPC method invalid requests",
   "type": "graph",
   "description": "The rate of invalid requests, all client side errors. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "requests / s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, method, errortype) (rate(diem_client_service_invalid_requests_count{type=~\"$requesttype\", method=~\"$method\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{job}}-{{method}}:{{errortype}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Method Internal Errors",
   "type": "graph",
   "description": "Internal error rate, likely a bug if there is data show up.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "errors / s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, method, errorcode) (rate(diem_client_service_internal_error_count{type=~\"$requesttype\", method=~\"$method\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{job}}-{{method}}:{{errorcode}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Method $requesttype Latency [P50]",
   "type": "graph",
   "description": "Latency of each method, for batch type request, this is individual method process latency, not total. \nCheck JSON-RPC Request Latency for total batch request processing latency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "repeat": "requesttype",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(diem_client_service_method_latency_seconds_bucket{job=~\"$job\",type=~\"$requesttype\", method=~\"$method\"}[$interval])) by (job, type, method, le))",
     "legendFormat": "{{job}}-{{method}}-{{type}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Method $requesttype Latency [P90]",
   "type": "graph",
   "description": "Latency of each method, for batch type request, this is individual method process latency, not total. \nCheck JSON-RPC Request Latency for total batch request processing latency.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "repeat": "requesttype",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(diem_client_service_method_latency_seconds_bucket{job=~\"$job\",type=~\"$requesttype\", method=~\"$method\"}[$interval])) by (job, type, method, le))",
     "legendFormat": "{{job}}-{{method}}-{{type}}"
    }
   ]
  },
  {
   "title": "JSON-RPC Method $requesttype Latency [P99]",
   "type": "graph",
   "description": "Latency of each method, for batch type request, this is individual method process latency, not total. \nCheck JSON-RPC Request Latency for total batch request processing latency.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "repeat": "requesttype",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(diem_client_service_method_latency_seconds_bucket{job=~\"$job\",type=~\"$requesttype\", method=~\"$method\"}[$interval])) by (job, type, method, le))",
     "legendFormat": "{{job}}-{{method}}-{{type}}"
    }
   ]
  }
 ]
}