{
 "title": "Mempool",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mempool size",
   "type": "graph",
   "description": "total number of transactions in mempool",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# keys" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"system_ttl\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful Txn Insertion Rate",
   "type": "graph",
   "description": "rate of mempool insertion of txn",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "txns / sec" }
   ],
   "targets": [
    {
     "expr": "sum by (job, status) (rate(diem_shared_mempool_transactions_processed{status=\"success\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{job}} - {{status}}"
    }
   ]
  },
  {
   "title": "Txn Removal Rate",
   "type": "graph",
   "description": "Rate at which txns are removed (via commit) from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "txns/sec" }
   ],
   "targets": [
    {
     "expr": "rate(diem_core_mempool_removed_txns_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Upstream Peers",
   "type": "graph",
   "description": "number of live peers a node can broadcast to in each network",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, network) (diem_mempool_active_upstream_peers_count{job=~\"$job\"})",
     "legendFormat": "{{job}}  ({{network}} network)"
    }
   ]
  },
  {
   "title": "VM Failed Txns Rate",
   "type": "graph",
   "description": "rate of submitted txns that failed to pass the VM validation",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "txn / s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, network, sender) (rate(diem_shared_mempool_transactions_processed{status=\"vm_validation\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{job}} <- ({{network}} network:{{sender}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mempool Service Timeout",
     "type": "graph",
     "description": "number of timeouts on a mempool service request (from consensus/state sync)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_service_latency_ms_count{result=\"fail\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}} - {{type}}"
      }
     ]
    },
    {
     "title": "DB error",
     "type": "graph",
     "description": "number of times a DB error occurred",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_db_error_count{job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "JSON RPC Callback Timeout",
     "type": "graph",
     "description": "number of timeouts in callback to JSON RPC",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_json_rpc_callback_fail_count{job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Network Send Fail",
     "type": "graph",
     "description": "number of times a diem network send failed",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_network_send_fail_count{job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "VM Reconfiguration Failure",
     "type": "graph",
     "description": "number of times reconfiguration of VM failed",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_vm_reconfig_update_fail_count{job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Core Mempool Invariant Violation",
     "type": "graph",
     "description": "number of times core mempool invariant was violated",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_core_mempool_invariant_violated_count{job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Unexpected Network Messages",
     "type": "graph",
     "description": "rate of unexpected network messages received",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_unexpected_network_count{job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}} <- {{network}}:{{peer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Core Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client-expired txns",
     "type": "graph",
     "description": "rate of number of transactions that expired in mempool based on client-specified expiration time",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "txns" }
     ],
     "targets": [
      {
       "expr": "rate(diem_core_mempool_gc_latency_count{type=\"client_expiration\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}} : {{status}}"
      }
     ]
    },
    {
     "title": "System-expired Txns",
     "type": "graph",
     "description": "Rate of number of transactions that expired in mempool based on mempool-specified expiration time",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "txns" }
     ],
     "targets": [
      {
       "expr": "rate(diem_core_mempool_gc_latency_count{type=\"system_ttl\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}} : {{status}}"
      }
     ]
    },
    {
     "title": "Parking Lot Index",
     "type": "graph",
     "description": "number of transactions in parking lot index. These transactions are not ready for broadcast or consensus",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "# keys" }
     ],
     "targets": [
      {
       "expr": "diem_core_mempool_index_size{index=\"parking_lot\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Timeline Index",
     "type": "graph",
     "description": "number of transactions ready for broadcast in core mempool ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "# keys" }
     ],
     "targets": [
      {
       "expr": "diem_core_mempool_index_size{index=\"timeline\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Priority Index",
     "type": "graph",
     "description": "transactions ready for consensus",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "# keys" }
     ],
     "targets": [
      {
       "expr": "diem_core_mempool_index_size{index=\"priority\", job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Failed Mempool Insertion Rate",
     "type": "graph",
     "description": "rate of transactions that passed VM validation but were rejected from mempool",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "failures / s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_shared_mempool_transactions_processed{status!=\"success\", status!=\"vm_validation\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}} <- ({{network}} network:{{sender}}) -  {{status}}"
      }
     ]
    },
    {
     "title": "Garbage Collection Event Rate",
     "type": "graph",
     "description": "Number of times garbage-collection event occurred (regardless of how many txns were actually removed in the event)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "events / s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_core_mempool_gc_event_count{type=\"system_ttl\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "GC Latency",
     "type": "graph",
     "description": "how long a transaction stayed in mempool before being garbage-collected",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_core_mempool_gc_latency_sum{job=~\"$job\"}[$interval])/rate(diem_core_mempool_gc_latency_count{job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  { "title": "Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Accepted Transaction Commit Rate",
   "type": "graph",
   "description": "Rate of accepted transactions committed per second (notified from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "accepted txns / sec" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_transactions_sum{type=\"commit_accepted\", job=~\"$job\"}[$interval])\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg latency for commit (accepted)",
   "type": "graph",
   "description": "average time it takes for mempool to process a commit of accepted transactions (sent from state sync)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_latency_ms_sum{type=\"commit_accepted\", job=~\"$job\"}[$interval]) / rate(diem_mempool_service_latency_ms_count{type=\"commit_accepted\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rejected Transaction Commit Rate",
   "type": "graph",
   "description": "rate of rejected committed transactions (notified from consensus)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "txns/sec" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_transactions_sum{type=\"commit_rejected\", job=~\"$job\"}[$interval])\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg time of commit (rejected txns)",
   "type": "graph",
   "description": "avg time it takes to process committed rejected txns",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_latency_ms_sum{type=\"commit_rejected\", job=~\"$job\"}[$interval])/rate(diem_mempool_service_latency_ms_count{type=\"commit_rejected\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "graph",
   "description": "Average size of consensus blocks pulled from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "avg block size" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_transactions_sum{type=\"get_block\", job=~\"$job\"}[$interval]) / rate(diem_mempool_service_transactions_count{type=\"get_block\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Avg latency for get_block",
   "type": "graph",
   "description": "Avg time it takes for consensus to pull block from mempool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_service_latency_ms_sum{type=\"get_block\", job=~\"$job\"}[$interval]) / rate(diem_mempool_service_latency_ms_count{type=\"get_block\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Shared mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  },
  {
   "title": "Incoming events rate",
   "type": "graph",
   "description": "rate of shared mempool events from peers",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "events/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_events{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} - {{event}}"
    }
   ]
  },
  {
   "title": "Shared Mempool Task Start Latency",
   "type": "graph",
   "description": "average time it takes for mempool to start an async task",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_mempool_bounded_executor_spawn_latency_sum{stage=\"start\", job=~\"$job\"}[$interval]) / rate(diem_mempool_bounded_executor_spawn_latency_count{stage=\"start\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} - {{task}}"
    }
   ]
  },
  {
   "title": "Incoming Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "New transactions received rate",
     "type": "graph",
     "description": "rate of new transactions received from other peers or JSON-RPC",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short", "label": "txns/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, network, sender) (rate(diem_shared_mempool_transactions_processed{job=~\"$job\"}[$interval]))",
       "legendFormat": "{{job}} <- ({{network}} network, {{sender}})"
      }
     ]
    },
    {
     "title": "Successful transaction validation rate",
     "type": "graph",
     "description": "rate of transactions that were successfully validated before mempool insertion\n",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "yaxes": [
      { "format": "short", "label": "txns/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, network, sender) (rate(diem_shared_mempool_transactions_processed{status!=\"vm_validation\", job=~\"$job\"}[$interval]))",
       "legendFormat": "{{job}} <- ({{network}} network:{{sender}})"
      }
     ]
    },
    {
     "title": "Average Txn Processing Latency",
     "type": "graph",
     "description": "avg time it takes to process incoming transactions, per incoming submission",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "s", "label": "sec / txn submission" }
     ],
     "targets": [
      {
       "expr": "rate(diem_shared_mempool_request_latency_sum{job=~\"$job\"}[$interval]) / rate(diem_shared_mempool_request_latency_count{job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}} <- ({{network}} network:{{sender}})"
      }
     ]
    },
    {
     "title": "Average VM Validation Latency",
     "type": "graph",
     "description": "avg time it takes to VM-validate txns in a submission",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_process_txn_breakdown_latency_sum{portion=\"vm_validation\", job=~\"$job\"}[$interval]) / rate(diem_mempool_process_txn_breakdown_latency_count{portion=\"vm_validation\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Average DB Read Latency",
     "type": "graph",
     "description": "latency of db read when validating transaction",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_mempool_process_txn_breakdown_latency_sum{portion=\"storage_fetch\", job=~\"$job\"}[$interval]) / rate(diem_mempool_process_txn_breakdown_latency_count{portion=\"storage_fetch\", job=~\"$job\"}[$interval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Txn Broadcasts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true
  },
  {
   "title": "Average Broadcast Size",
   "type": "graph",
   "description": "average number of transactions in a single broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "txns / broadcast" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_transaction_broadcast_sum{job=~\"$job\"}[$interval]) / rate(diem_shared_mempool_transaction_broadcast_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} -> ({{network}} network:{{recipient}})"
    }
   ]
  },
  {
   "title": "Broadcasted Txns Rate",
   "type": "graph",
   "description": "rate of transactions broadcasted to other peers",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "txns/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_transaction_broadcast_sum{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} -> ({{network}} network:{{recipient}})"
    }
   ]
  },
  {
   "title": "Broadcast Rate",
   "type": "graph",
   "description": "avg number of broadcasts / sec",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "broadcasts / sec" }
   ],
   "targets": [
    {
     "expr": "rate(diem_broadcast_latency_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} -> ({{network}} network:{{recipient}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Execution Latency",
   "type": "graph",
   "description": "avg time it takes to execute a broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s", "label": "secs / broadcast" }
   ],
   "targets": [
    {
     "expr": "rate(diem_broadcast_latency_sum{job=~\"$job\"}[$interval]) / rate(diem_broadcast_latency_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} -> ({{network}} network,{{recipient}})"
    }
   ]
  },
  {
   "title": "Average Broadcast Roundtrip Time",
   "type": "graph",
   "description": "average time b/w broadcast sent and ACK coming back for it",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_broadcast_roundtrip_latency_sum{job=~\"$job\"}[$interval]) / rate(diem_shared_mempool_broadcast_roundtrip_latency_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} -> ({{network}} network:{{recipient}})"
    }
   ]
  },
  {
   "title": "Pending Broadcasts",
   "type": "graph",
   "description": "number of sent broadcasts awaiting an ACK",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "# broadcasts" }
   ],
   "targets": [
    {
     "expr": "diem_shared_mempool_pending_broadcasts_count{job=~\"$job\"}",
     "legendFormat": "{{job}} -> ({{network}}:{{recipient}})"
    }
   ]
  },
  {
   "title": "Expired Rebroadcast Rate",
   "type": "graph",
   "description": "rate of broadcasts that are retrying expired braodcasts (that did not get back an ACK in window of time)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "expired / s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_rebroadcast_count{type=\"expired\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} -> {{network}}:{{recipient}}"
    }
   ]
  },
  {
   "title": "Retry Rebroadcast",
   "type": "graph",
   "description": "rate of broadcasts that are retrying past broadcasts that received a retry ACK",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_rebroadcast_count{type=\"retry\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} -> ({{network}}:{{recipient}})"
    }
   ]
  },
  {
   "title": "Backpressure Broadcast",
   "type": "graph",
   "description": "rate of broadcasts that were executed as a backpressure broadcast",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_rebroadcast_count{type=\"backpressure\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} -> {{network}}:{{recipient}}"
    }
   ]
  },
  {
   "title": "ACKs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true
  },
  {
   "title": "Sent ACKs (backoff/retry)",
   "type": "graph",
   "description": "rate of backoff/retry ACKs sent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_shared_mempool_ack_count{direction=\"sent\", job=~\"$job\"}",
     "legendFormat": "{{job}} -> {{network}}:{{recipient}} - {{type}}"
    }
   ]
  },
  {
   "title": "ACKs Received",
   "type": "graph",
   "description": "rate of retry/backpressure ACKs received",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(diem_shared_mempool_ack_count{direction=\"received\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}} <- {{network}}:{{recipient}} - {{type}}"
    }
   ]
  },
  {
   "title": "Network Sender",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true
  },
  {
   "title": "Dropped Messages",
   "type": "graph",
   "description": "number of messages dropped from mempool channel sender",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mempool_pending_network_events{state=\"dropped\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Messages Enqueued Rate",
   "type": "graph",
   "description": "rate of messages being enqueued to be sent out",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mempool_pending_network_events{state=\"enqueued\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Messages Dequeued Rate",
   "type": "graph",
   "description": "Rate of messages dequeued from mempool network sender",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mempool_pending_network_events{state=\"dequeued\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Messages Queued",
   "type": "graph",
   "description": "Messages currently queued to be sent out",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (mempool_pending_network_events{state=\"enqueued\", job=~\"$job\"}) - sum by (job)  (mempool_pending_network_events{state=\"dequeued\", job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}