{
 "title": "Network",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network_id", "query": { "query": "label_values(network_id)" } },
   { "name": "role_type", "query": { "query": "label_values(role_type)" } },
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   { "name": "rpc_protocol", "label": "RPC Protocol", "query": { "query": "label_values(protocol_id)" } },
   { "name": "AggInterval", "label": "Aggregation Interval", "query": "1m,5m,15m,30m,1h,3h,1d,7d" },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Connected Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Connected Peers",
   "type": "graph",
   "description": "Total Connected Peers for both inbound and outbound per peer.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id) (diem_connections{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\"})\n",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Inbound Connected Peers",
   "type": "graph",
   "description": "Total Inbound connected peers.  There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id) (diem_connections{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", direction=\"inbound\"})",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Outbound Connected Peers",
   "type": "graph",
   "description": "Total outbound connections per peer.  Every node should have an outbound connection.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id)(diem_connections{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", direction=\"outbound\"})",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Network Key Mismatches",
   "type": "graph",
   "description": "Value is > 0 if there is a mismatch between onchain and actual network key on the interface",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (job, role_type, network_id) (diem_network_key_mismatch{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\"})",
     "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Traffic and Rate Limiting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "VFN Public Network Inbound Allowed bytes (bytes/s)",
     "type": "graph",
     "description": "Inbound number of bytes passed through the throttler",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_network_rate_limit_sum{metric=\"allowed\", direction=\"inbound\", job=~\"$job\"}[$AggInterval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "VFN Public Network Outbound Allowed bytes (bytes/s)",
     "type": "graph",
     "description": "Outbound number of bytes passed through the throttler",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_network_rate_limit_sum{metric=\"allowed\", direction=\"outbound\", job=~\"$job\"}[$AggInterval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "VFN Public Network Inbound Throttled bytes (bytes/s)",
     "type": "graph",
     "description": "Inbound number of bytes rate limited through the throttler",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_network_rate_limit_sum{metric=\"throttled\", direction=\"inbound\", job=~\"$job\"}[$AggInterval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "VFN Public Network Outbound Throttled bytes (bytes/s)",
     "type": "graph",
     "description": "Outbound number of bytes rate limited through the throttler",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "rate(diem_network_rate_limit_sum{metric=\"throttled\", direction=\"outbound\", job=~\"$job\"}[$AggInterval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Notifications Queued",
     "type": "graph",
     "description": "TBD",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(diem_network_pending_network_notifications{job=~\"$job\",state=\"enqueued\"}) - sum by (job)(diem_network_pending_network_notifications{job=~\"$job\",state=\"dequeued\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Peer Manager Requests Queued",
     "type": "graph",
     "description": "TBD",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(diem_network_pending_peer_manager_requests{job=~\"$job\",state=\"enqueued\"}) - sum by (job)(diem_network_pending_peer_manager_requests{job=~\"$job\",state=\"dequeued\"})",
       "legendFormat": "{{owner}}-{{role}}"
      }
     ]
    },
    {
     "title": "Network Requests Queued",
     "type": "graph",
     "description": "TBD",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(diem_network_pending_requests{job=~\"$job\",state=\"enqueued\"}) - sum by (job)(diem_network_pending_requests{job=~\"$job\",state=\"dequeued\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Pending Health Check Events Queued",
     "type": "graph",
     "description": "TBD",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (job)(diem_network_pending_health_check_events{job=~\"$job\",state=\"enqueued\"}) - sum by (job)(diem_network_pending_health_check_events{job=~\"$job\",state=\"dequeued\"})",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Pending Wire Messages",
     "type": "graph",
     "description": "TBD",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(diem_network_pending_wire_messages{job=~\"$job\"}[$AggInterval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Pending Connectivity Manager Requests",
     "type": "graph",
     "description": "TBD",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(diem_network_pending_connectivity_manager_requests{job=~\"$job\"}[$AggInterval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queuing Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Messages Drop Rate",
     "type": "graph",
     "description": "RPCs declined or canceled due to hitting max RPC capacity or max queue capacity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(diem_network_rpc_messages{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=~\"(declined|canceled)\"}[$AggInterval])",
       "legendFormat": "{{job}}-{{role_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "New Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Pending Connection Upgrades",
     "type": "graph",
     "description": "The rate of new inbound connections on the network interface",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id) (rate(diem_network_pending_connection_upgrades{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", direction=\"inbound\" }[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Outbound Pending Connection Upgrades",
     "type": "graph",
     "description": "The rate of new outbound connections on the network interface",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id) (rate(diem_network_pending_connection_upgrades{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", direction=\"outbound\" }[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Inbound Connection Upgrade Latency [P50]",
     "type": "graph",
     "description": "Latency of Inbound connection upgrades",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, role_type, network_id, le) (rate(diem_network_connection_upgrade_time_seconds_bucket{direction=\"inbound\",role_type=~\"$role_type\",job=~\"$job\",network_id=~\"$network_id\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Outbound Connection Upgrade Latency [P50]",
     "type": "graph",
     "description": "Latency of Outbound connection upgrades",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, role_type, network_id, le) (rate(diem_network_connection_upgrade_time_seconds_bucket{direction=\"outbound\",role_type=~\"$role_type\",job=~\"$job\",network_id=~\"$network_id\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Inbound Connection Upgrade Latency [P90]",
     "type": "graph",
     "description": "Latency of Inbound connection upgrades",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (job, role_type, network_id, le) (rate(diem_network_connection_upgrade_time_seconds_bucket{direction=\"inbound\",role_type=~\"$role_type\",job=~\"$job\",network_id=~\"$network_id\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Outbound Connection Upgrade Latency [P90]",
     "type": "graph",
     "description": "Latency of Outbound connection upgrades",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (job, role_type, network_id, le) (rate(diem_network_connection_upgrade_time_seconds_bucket{direction=\"outbound\",role_type=~\"$role_type\",job=~\"$job\",network_id=~\"$network_id\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Inbound Connection Upgrade Latency [P99]",
     "type": "graph",
     "description": "Latency of Inbound connection upgrades",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (job, role_type, network_id, le) (rate(diem_network_connection_upgrade_time_seconds_bucket{direction=\"inbound\",role_type=~\"$role_type\",job=~\"$job\",network_id=~\"$network_id\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Outbound Connection Upgrade Latency [P99]",
     "type": "graph",
     "description": "Latency of Outbound connection upgrades",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (job, role_type, network_id, le) (rate(diem_network_connection_upgrade_time_seconds_bucket{direction=\"outbound\",role_type=~\"$role_type\",job=~\"$job\",network_id=~\"$network_id\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Total Request Error Rate (% requests in error)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(network_id, role_type, job) (rate(diem_network_rpc_messages{network_id=~\"$network_id\",role_type=~\"$role_type\",job=~\"$job\",type=\"request\",state=\"failed\"}[$AggInterval])) / sum by(network_id, role_type, job) (rate(diem_network_rpc_messages{network_id=~\"$network_id\",role_type=~\"$role_type\",job=~\"$job\",type=\"request\",state=~\"(sent|failed)\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "RPC Total Response Error Rate (% responses in error)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(network_id, role_type, job) (rate(diem_network_rpc_messages{network_id=~\"$network_id\",role_type=~\"$role_type\",job=~\"$job\",type=\"response\",state=\"failed\"}[$AggInterval])) / sum by(network_id, role_type, job) (rate(diem_network_rpc_messages{network_id=~\"$network_id\",role_type=~\"$role_type\",job=~\"$job\",type=\"request\",state=\"received\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Throughput of Total Outbound RPCs (bytes/s)",
     "type": "graph",
     "description": "Total throughput of all Outbound RPC requests per peer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id) (rate(diem_network_rpc_bytes{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"sent\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Throughput of Total Inbound RPCs (bytes/s)",
     "type": "graph",
     "description": "Total throughput of all Inbound RPC requests per peer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id)(rate(diem_network_rpc_bytes{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"received\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Rate of Total Outbound RPCs (msg/s)",
     "type": "graph",
     "description": "Total number of all Outbound RPC requests per peer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "msg/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id)(rate(diem_network_rpc_messages{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", type=\"request\",state=\"sent\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Rate of Total Inbound RPCs (msg/s)",
     "type": "graph",
     "description": "Total number of all Inbound RPC requests per peer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "msg/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id)(rate(diem_network_rpc_messages{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", type=\"request\", state=\"received\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Latency of $rpc_protocol Outbound RPCs [P50]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, network_id, role_type, le)(rate(diem_network_outbound_rpc_request_latency_seconds_bucket{protocol_id=~\"$rpc_protocol\",job=~\"$job\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Latency of $rpc_protocol Inbound RPCs [P50]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (job, network_id, role_type, le)(rate(diem_network_inbound_rpc_handler_latency_seconds_bucket{protocol_id=~\"$rpc_protocol\",job=~\"$job\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Latency of $rpc_protocol Outbound RPCs [P90]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (job, network_id, role_type, le)(rate(diem_network_outbound_rpc_request_latency_seconds_bucket{protocol_id=~\"$rpc_protocol\",job=~\"$job\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Latency of $rpc_protocol Inbound RPCs [P90]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (job, network_id, role_type, le)(rate(diem_network_inbound_rpc_handler_latency_seconds_bucket{protocol_id=~\"$rpc_protocol\",job=~\"$job\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Latency of $rpc_protocol Outbound RPCs [P99]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (job, network_id, role_type, le)(rate(diem_network_outbound_rpc_request_latency_seconds_bucket{protocol_id=~\"$rpc_protocol\",job=~\"$job\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Latency of $rpc_protocol Inbound RPCs [P99]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (job, network_id, role_type, le)(rate(diem_network_inbound_rpc_handler_latency_seconds_bucket{protocol_id=~\"$rpc_protocol\",job=~\"$job\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Direct Send",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput of Total Outbound Direct Sends (bytes/s)",
     "type": "graph",
     "description": "Total throughput of all Outbound Direct Send requests per peer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id)(rate(diem_network_direct_send_bytes{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"sent\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Throughput of Total Inbound Direct Sends (bytes/s)",
     "type": "graph",
     "description": "Total throughput of all Inbound Direct Send requests per peer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id)(rate(diem_network_direct_send_bytes{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"received\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Rate of Total Outbound Direct Sends (msg/s)",
     "type": "graph",
     "description": "Total number of all Outbound Direct Send requests per peer",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "msg/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id)(rate(diem_network_direct_send_messages{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"sent\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    },
    {
     "title": "Rate of Total Inbound Direct Sends (msg/s)",
     "type": "graph",
     "description": "Total number of all Inbound Direct Send requests per peer",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "msg/s" }
     ],
     "targets": [
      {
       "expr": "sum by (job, role_type, network_id)(rate(diem_network_direct_send_messages{network_id=~\"$network_id\", role_type=~\"$role_type\", job=~\"$job\", state=\"received\"}[$AggInterval]))",
       "legendFormat": "{{job}}-{{role_type}}-{{network_id}}"
      }
     ]
    }
   ]
  }
 ]
}