{
 "title": "Safety Rules",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Safety Rules Query Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Counts of Safety Rules Queries",
   "type": "graph",
   "description": "This panel displays the error counts encountered by safety rules queries within the last aggregation interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    {
     "format": "short",
     "label": "Error Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{job=~\"$job\", result=\"error\"}[$interval])",
     "legendFormat": "{{job}}_{{method}}"
    }
   ]
  },
  { "title": "Safety Rules Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Epoch",
   "type": "graph",
   "description": "The most recent epoch processed by safety rules",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Epoch Number" }
   ],
   "targets": [
    {
     "expr": "diem_safety_rules_state{field=\"epoch\", owner=~\"$owner\"}",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Last Voted Round",
   "type": "graph",
   "description": "The last round that the validator submitted a vote",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Round Number" }
   ],
   "targets": [
    {
     "expr": "diem_safety_rules_state{field=\"last_voted_round\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Preferred Round",
   "type": "graph",
   "description": "The highest parent round from any incoming quorum certificate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Round Number" }
   ],
   "targets": [
    {
     "expr": "diem_safety_rules_state{field=\"preferred_round\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Waypoint Version",
   "type": "graph",
   "description": "Current waypoint version of persistent safety storage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Waypoint Version" }
   ],
   "targets": [
    {
     "expr": "diem_safety_rules_state{field=\"waypoint_version\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Safety Rules Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Initialize",
   "type": "graph",
   "description": "This method initializes safety rules using an epoch ending ledger info.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{method=\"initialize\", job=~\"$job\"}[$interval])",
     "legendFormat": "{{job}}_{{result}}"
    }
   ]
  },
  {
   "title": "Consensus State",
   "type": "graph",
   "description": "This method provides the internal state of safety rules for monitoring and/or debugging purposes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{job=~\"$job\", method=\"consensus_state\"}[$interval])",
     "legendFormat": "{{job}}_{{result}}"
    }
   ]
  },
  {
   "title": "Construct and Sign Vote",
   "type": "graph",
   "description": "This method attempts to vote for a given proposal following the voting rules.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{job=~\"$job\", method=\"construct_and_sign_vote\"}[$interval])",
     "legendFormat": "{{job}}_{{result}}"
    }
   ]
  },
  {
   "title": "Sign Proposal",
   "type": "graph",
   "description": "This method is called to sign a proposal or block.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{job=~\"$job\", method=\"sign_proposal\"}[$interval])",
     "legendFormat": "{{job}}_{{result}}"
    }
   ]
  },
  {
   "title": "Sign Timeout",
   "type": "graph",
   "description": "This method is called to sign a timeout.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    {
     "format": "short",
     "label": "Result Count (last aggregation interval)"
    }
   ],
   "targets": [
    {
     "expr": "increase(diem_safety_rules_queries{job=~\"$job\", method=\"sign_timeout\"}[$interval])",
     "legendFormat": "{{job}}_{{result}}"
    }
   ]
  }
 ]
}