{
 "title": "0L - Experiments",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Validator overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Validators",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(diem_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Outbound connections",
   "type": "piechart",
   "description": "Number of current outbound connections",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(diem_connections{direction=\"outbound\"}) by (peer_id)",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "piechart",
   "description": "Number of current inbound connections",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (diem_connections{direction=\"inbound\"}) by (peer_id)",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  { "title": "Round", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Round",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "diem_consensus_current_round", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Current Round",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "diem_consensus_current_round{}" }
   ]
  },
  { "title": "Epoch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Current Epoch",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "diem_consensus_epoch", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Current Epochs",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 21 },
   "targets": [
    { "expr": "diem_consensus_epoch" }
   ]
  }
 ]
}