{
 "title": "Diversity",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Region Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(count by (failure_domain_beta_kubernetes_io_region\n) (count by (owner, failure_domain_beta_kubernetes_io_region\n) (kubelet_volume_stats_used_bytes))) / ignoring(failure_domain_beta_kubernetes_io_region) group_left count(count by (owner, failure_domain_beta_kubernetes_io_region\n) (kubelet_volume_stats_used_bytes))",
     "legendFormat": "{{failure_domain_beta_kubernetes_io_region}}"
    }
   ]
  },
  {
   "title": "Cloud Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"ip.*\"})) / (count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"ip.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"aks.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"gke.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"scw.*\"})))",
     "legendFormat": "AWS"
    },
    {
     "expr": "count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"aks.*\"})) / (count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"ip.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"aks.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"gke.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"scw.*\"})))",
     "legendFormat": "Azure"
    },
    {
     "expr": "count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"gke.*\"})) / (count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"ip.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"aks.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"gke.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"scw.*\"})))",
     "legendFormat": "GCP"
    },
    {
     "expr": "count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"scw.*\"})) / (count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"ip.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"aks.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"gke.*\"})) + count(count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"scw.*\"})))",
     "legendFormat": "Scaleway"
    }
   ]
  },
  {
   "title": "Server Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (beta_kubernetes_io_instance_type\n) (count by (owner, beta_kubernetes_io_instance_type\n) (kubelet_volume_stats_used_bytes))",
     "legendFormat": "{{beta_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Region<>Node Mapping",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (owner, failure_domain_beta_kubernetes_io_region\n) (kubelet_volume_stats_used_bytes)",
     "legendFormat": "{{owner}}-{{failure_domain_beta_kubernetes_io_region}}"
    }
   ]
  },
  {
   "title": "Cloud<>Node Mapping",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"ip.*\"})",
     "legendFormat": "{{owner}}-AWS"
    },
    {
     "expr": "count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"aks.*\"})",
     "legendFormat": "{{owner}}-Azure"
    },
    {
     "expr": "count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"gke.*\"})",
     "legendFormat": "{{owner}}-GCP"
    },
    {
     "expr": "count by (owner) (kubelet_volume_stats_used_bytes{instance=~\"scw.*\"})",
     "legendFormat": "{{owner}}-Scaleway"
    }
   ]
  },
  {
   "title": "Kubernetes Node Versions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kubernetes_build_info) by (owner, git_version)",
     "legendFormat": "{{owner}}-{{git_version}}"
    }
   ]
  }
 ]
}