{
 "title": "Key Manager",
 "description": "The operations performed by the Key Manager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "owner", "query": { "query": "label_values(owner)" } }
  ]
 },
 "panels": [
  {
   "title": "Consensus Key Rotations (Last 30 Days)",
   "type": "graph",
   "description": "This panel tracks the number of successful consensus key rotations in the last 30 days. More specifically, it tracks: (i) the number of consensus key rotations in storage; and (ii) the number of consensus rotation transactions submitted to the blockchain.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of rotation operations" }
   ],
   "targets": [
    {
     "expr": "increase(diem_key_manager_state{state=\"rotated_in_storage\"}[30d])",
     "legendFormat": "{{owner}}_rotated_in_storage"
    },
    {
     "expr": "increase(diem_key_manager_state{state=\"submitted_rotation_transaction\"}[30d])",
     "legendFormat": "{{owner}}_submitted_rotation_transaction"
    }
   ]
  },
  {
   "title": "Errors Encountered (Last Hour)",
   "type": "graph",
   "description": "This panel tracks the number of errors encountered by the key manager during execution in the last hour. More specifically, we track two error types: (i) liveness errors; and (ii) unexpected errors.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of errors" }
   ],
   "targets": [
    {
     "expr": "increase(diem_key_manager_state{state=\"liveness_error_encountered\", owner=~\"$owner\"}[1h])",
     "legendFormat": "{{owner}}_liveness_error"
    },
    {
     "expr": "increase(diem_key_manager_state{state=\"unexpected_error_encountered\", owner=~\"$owner\"}[1h])",
     "legendFormat": "{{owner}}_unexpected_error"
    }
   ]
  },
  {
   "title": "No Action Taken (Last Hour)",
   "type": "graph",
   "description": "This panel tracks the number of times the key manager decides to take no action after checking the keys because the keys are still fresh (in the last hour).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Number of no actions taken" }
   ],
   "targets": [
    {
     "expr": "increase(diem_key_manager_state{state=\"keys_still_fresh\", owner=~\"$owner\"}[1h])",
     "legendFormat": "{{owner}}_keys_still_fresh"
    }
   ]
  },
  {
   "title": "Waiting For Event (Last Hour)",
   "type": "graph",
   "description": "This panel tracks the number of times the key manager is blocked waiting for an event in the last hour. Specifically, we count: (i) the number waits for a reconfiguration event; and (ii) the number of waits for a rotation transaction to be executed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Number of wait events" }
   ],
   "targets": [
    {
     "expr": "increase(diem_key_manager_state{state=\"waiting_on_reconfiguration\", owner=~\"$owner\"}[1h])",
     "legendFormat": "{{owner}}_wait_for_reconfiguration"
    },
    {
     "expr": "increase(diem_key_manager_state{state=\"waiting_on_transaction_execution\", owner=~\"$owner\"}[1h])",
     "legendFormat": "{{owner}}_wait_for_transaction_execution"
    }
   ]
  }
 ]
}