{
 "title": "System",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "container", "query": { "query": "label_values(container)" } },
   { "name": "owner", "query": { "query": "label_values(owner)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"$container\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}-{{container}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_name=~\"$container\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}-{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=~\"$container\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{container}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container_name=~\"$container\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=~\"$container\", owner=~\"$owner\"} / container_spec_memory_limit_bytes{container=~\"$container\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{container}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container_name=~\"$container\", owner=~\"$owner\"} / container_spec_memory_limit_bytes{container_name=~\"$container\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{container_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*-($container)-e.*\", owner=~\"$owner\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*-($container)-e.*\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*($container)-e.*\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{owner=~\"$owner\", pod=~\".+$container(-e[0-9]+)?-0\"}[$interval]) + rate(container_network_transmit_bytes_total{owner=~\"$owner\", pod=~\".+$container(-e[0-9]+)?-0\"}[$interval])",
     "legendFormat": "{{owner}}-{{pod}}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{owner=~\"$owner\", pod_name=~\".+$container(-e[0-9]+)?-0\"}[$interval]) + rate(container_network_transmit_bytes_total{owner=~\"$owner\", pod_name=~\".+$container(-e[0-9]+)?-0\"}[$interval])",
     "legendFormat": "{{owner}}-{{pod_name}}"
    }
   ]
  },
  {
   "title": "IO Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{container=~\"$container\", owner=~\"$owner\"}[$interval]) + rate(container_fs_writes_total{container=~\"$container\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}-{{pod}}:{{container}}:{{device}}"
    },
    {
     "expr": "rate(container_fs_reads_total{container_name=~\"$container\", owner=~\"$owner\"}[$interval]) + rate(container_fs_writes_total{container_name=~\"$container\", owner=~\"$owner\"}[$interval])",
     "legendFormat": "{{owner}}-{{pod_name}}:{{container_name}}:{{device}}"
    }
   ]
  }
 ]
}