{
 "title": "Validator monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "diem_consensus_epoch" } },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Validator Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Epoch",
   "type": "gauge",
   "description": "Current epoch num",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_epoch{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Last committed round",
   "type": "gauge",
   "description": "This counter is set to the round of the highest committed block.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_last_committed_round{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "gauge",
   "description": "Total number of errors in main loop",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_error_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Last committed version",
   "type": "gauge",
   "description": "The counter corresponds to the version of the last committed ledger info",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_last_committed_version{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "timeseries",
   "description": "Count of the transactions since last restart. state is success or failed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(diem_consensus_committed_txns_count{job=\"$job\", state=\"success\"}[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(diem_consensus_committed_txns_count{job=\"$job\", state=\"retry\"}[$__rate_interval])",
     "legendFormat": "Retry"
    },
    {
     "expr": "increase(diem_consensus_committed_txns_count{job=\"$job\", state=\"failed\"}[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Transaction exec time",
   "type": "bargauge",
   "description": "Execution time per user transaction (in seconds)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(diem_vm_txn_total_seconds_bucket{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Committed blocks",
   "type": "timeseries",
   "description": "Count of the committed blocks since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "increase(diem_consensus_committed_blocks_count{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Transactions validated",
   "type": "timeseries",
   "description": "Number of transactions processed by the validator, with either \"success\" or \"failure\" labels",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(diem_vm_transactions_validated{job=~\"$job\", status=\"success\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "increase(diem_vm_transactions_validated{job=~\"$job\", status=\"failure\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Transactions per committed block",
   "type": "bargauge",
   "description": "Histogram for the number of txns per (committed) blocks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(diem_consensus_num_txns_per_block_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block tracing",
   "type": "bargauge",
   "description": "Histogram for different stages of a block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (increase(diem_consensus_block_tracing_bucket{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  { "title": "Round", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Last local round",
   "type": "gauge",
   "description": "This counter is set to the last round reported by the local round_state",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_current_round{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Round timeout ms",
   "type": "gauge",
   "description": "The timeout of the current round.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_round_timeout_s{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Local Round",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "diem_consensus_current_round{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Timeout rounds",
   "type": "timeseries",
   "description": "Count of the timeout rounds since last restart (close to 0 in happy path) including the number of timeouts a node experienced since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(diem_consensus_timeout_rounds_count{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Timeout rounds"
    },
    {
     "expr": "increase(diem_consensus_timeout_count{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Timeouts"
    }
   ]
  },
  {
   "title": "QC Rounds",
   "type": "timeseries",
   "description": "Count of the rounds that gathered QC since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "increase(diem_consensus_qc_rounds_count{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Proposal election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Committed proposal in window",
   "type": "gauge",
   "description": "Total number of this validator's committed proposals in the current reputation window",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_committed_proposals_in_window{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Committed votes in window",
   "type": "gauge",
   "description": "Total number of this validator's committed votes in the current reputation window",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_committed_votes_in_window{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block proposals sent",
   "type": "timeseries",
   "description": "Count of the block proposals sent by this validator since last restart (both primary and secondary)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "increase(diem_consensus_proposals_count{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Vote nil count",
   "type": "timeseries",
   "description": "Count the number of times a validator voted for a nil block since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "increase(diem_consensus_vote_nil_count{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Pending round timeouts",
   "type": "gauge",
   "description": "Count of the pending outbound round timeouts",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_pending_round_timeouts{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Pending self messages",
   "type": "gauge",
   "description": "Count of the pending messages sent to itself in the channel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_pending_self_messages{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Pending consensus network events",
   "type": "timeseries",
   "description": "Counters (queued, dequeued, dropped) related to pending network notifications to Consensus",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "increase(diem_consensus_pending_network_events{job=\"$job\",state=\"enqueued\"}[$__rate_interval])",
     "legendFormat": "enqueued"
    },
    {
     "expr": "increase(diem_consensus_pending_network_events{job=\"$job\",state=\"dequeued\"}[$__rate_interval])",
     "legendFormat": "dequeued"
    },
    {
     "expr": "increase(diem_consensus_pending_network_events{job=\"$job\",state=\"dropped\"}[$__rate_interval])",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Consensus channel messages",
   "type": "timeseries",
   "description": "Counters (queued, dequeued, dropped) related to consensus channel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "increase(diem_consensus_channel_msgs_count{job=\"$job\",state=\"enqueued\"}[$__rate_interval])",
     "legendFormat": "enqueued"
    },
    {
     "expr": "increase(diem_consensus_channel_msgs_count{job=\"$job\",state=\"dequeued\"}[$__rate_interval])",
     "legendFormat": "dequeued"
    },
    {
     "expr": "increase(diem_consensus_channel_msgs_count{job=\"$job\",state=\"dropped\"}[$__rate_interval])",
     "legendFormat": "dropped"
    }
   ]
  },
  {
   "title": "Block retrieval channel messages",
   "type": "timeseries",
   "description": "Counters (queued, dequeued, dropped) related to block retrieval channel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "increase(diem_consensus_block_retrieval_channel_msgs_count{job=\"$job\",state=\"enqueued\"}[$__rate_interval])",
     "legendFormat": "enqueued"
    },
    {
     "expr": "increase(diem_consensus_block_retrieval_channel_msgs_count{job=\"$job\",state=\"dequeued\"}[$__rate_interval])",
     "legendFormat": "dequeued"
    },
    {
     "expr": "increase(diem_consensus_block_retrieval_channel_msgs_count{job=\"$job\",state=\"dropped\"}[$__rate_interval])",
     "legendFormat": "dropped"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Sync info msgs sent",
   "type": "gauge",
   "description": "Counts the number of times the sync info message has been set since last restart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_sync_info_msg_sent_count{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks in tree",
   "type": "gauge",
   "description": "Counter for the number of blocks in the block tree (including the root)",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diem_consensus_num_blocks_in_tree{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}