{
 "title": "Validator Connectivity",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "owner",
    "query": {
     "query": "label_values(diem_network_peer_connected, owner)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ValidatorSet",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, diem_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Down node %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (count(rate(diem_consensus_current_round[10m]) > 0) OR on() vector(0)) / quantile(0.67, diem_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Not reporting metrics",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"federate\"} == 0 or up{job=\"diem-procs\", role=\"validator\"} == 0"
    }
   ]
  },
  {
   "title": "Node not Participating Consensus",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "rate(diem_consensus_current_round{role=\"validator\"}[1m]) == 0"
    }
   ]
  },
  { "title": "Connected Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Connected Peers",
   "type": "graph",
   "description": "Total Connected Peers for both inbound and outbound per peer.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id) (diem_connections{network_id=\"Validator\", role_type=\"validator\", owner=~\"$owner\"})\n",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Inbound Connected Peers",
   "type": "graph",
   "description": "Total Inbound connected peers. There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id) (diem_connections{network_id=\"Validator\", role_type=\"validator\", owner=~\"$owner\", direction=\"inbound\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Outbound Connected Peers",
   "type": "graph",
   "description": "Total outbound connections per peer. Every node should have an outbound connection.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id)(diem_connections{network_id=\"Validator\", role_type=\"validator\", owner=~\"$owner\", direction=\"outbound\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  { "title": "Connectivity Matrix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Current Validator Connections",
   "type": "table",
   "description": "An adjacency matrix showing each (validator -> remote validator) connection. Each row shows the \"owner\" node's view of its own connections to each other validator.\n\nA green \"1\" means there is currently a connection, while a red \"0\" means the nodes are not currently connected. An empty square means there is no reported metric for this (owner_i, owner_j) pair, which is expected for (owner_i, owner_i) since we don't allow self-connections.",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# Filter out extraneous fields.\nsum by (owner, remote_owner) (\n  (\n    diem_network_peer_connected{network_id=\"Validator\", role_type=\"validator\"}\n\n  # Do a left join on a table containing labels [\"remote_peer_id\", \"remote_owner\"]\n  # to join in \"remote_owner\" for each \"remote_peer_id\".\n  ) + on(remote_peer_id) group_left(remote_owner) (\n\n    # We can only left join with certain bin-ops, so we force all values to zero\n    # here so we can add without messing up the connection values.\n    clamp_max(\n      # Filter out extraneous fields.\n      sum by (remote_owner, remote_peer_id) (\n        sum without (direction) (\n          # Rename \"peer_id\" -> \"remote_peer_id\" and \"owner\" -> \"remote_owner\" so\n          # these fields don't conflict with those from peer_connected.\n          label_replace(\n            label_replace(\n              diem_connections{network_id=\"Validator\", role_type=\"validator\"},\n              \"remote_peer_id\", \"$1\",\n              \"peer_id\", \"(.*)\"\n            ),\n            \"remote_owner\", \"$1\",\n            \"owner\", \"(.*)\"\n          )\n        )\n      ),\n      0\n    )\n  )\n)"
    }
   ]
  }
 ]
}