{
 "title": "0L Move",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Active Validators",
    "query": {}
   },
   {
    "name": "ol_node_type",
    "label": "Node Type",
    "query": "Validator : validator, VFN : vfn, Fullnode : fullnode"
   },
   {
    "name": "interval",
    "label": "Aggregation interval",
    "query": "15s,30s,1m,5m,10m,15m,30m,1h,2h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "discord_ex", "label": "Exclude Discord Regex", "query": "zmanian.+" }
  ]
 },
 "panels": [
  { "title": "Validators Only", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency to execute a single transaction in the VM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(diem_vm_executor_single_tx_latency_sum{job=~\"$job\", ol_discord!~\"$discord_ex\"}[$interval])\n/\nrate(diem_vm_executor_single_tx_latency_count{job=~\"$job\", ol_discord!~\"$discord_ex\"}[$interval])",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "Latency to verify a VDF challenge",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(diem_move_vm_native_verify_vdf_latency_sum{job=~\"$job\", ol_discord!~\"$discord_ex\"}[$interval])\n/\nrate(diem_move_vm_native_verify_vdf_latency_count{job=~\"$job\", ol_discord!~\"$discord_ex\"}[$interval])",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "How many VDF proofs cannot be processed because of formal errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(diem_move_vm_native_verify_vdf_proof_error_count{job=~\"$job\", ol_discord!~\"$discord_ex\"}[$interval])",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "How many VDF proofs are submitted",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(diem_move_vm_native_verify_vdf_proof_count{job=~\"$job\", ol_discord!~\"$discord_ex\"}[$interval])",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  {
   "title": "Latency of mempool processing request from consensus/state sync",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(diem_mempool_service_latency_ms_sum{job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_discord!~\"$discord_ex\"}[$interval])\n/\nrate(diem_mempool_service_latency_ms_count{job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_discord!~\"$discord_ex\"}[$interval])",
     "legendFormat": "id-{{job}}-id {{ol_node_type}} @{{ol_discord}} {{type}} {{result}}"
    }
   ]
  }
 ]
}