{
 "title": "0L Node",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Active Validators",
    "query": {}
   },
   {
    "name": "ol_node_type",
    "label": "Node Type",
    "query": "Validator : validator, VFN : vfn, Fullnode : fullnode"
   },
   {
    "name": "interval",
    "label": "Aggregation interval",
    "query": "15s,30s,1m,5m,10m,15m,30m,1h,2h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "discord_ex", "label": "Exclude Discord Regex", "query": "zmanian.+" }
  ]
 },
 "panels": [
  { "title": "Validators Only", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Committed blocks per sec",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(diem_consensus_last_committed_round{job=~\"$job\", ol_discord!~\"$discord_ex\"}[$interval])",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "Block creation to commit",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(diem_consensus_block_tracing_sum{job=~\"$job\", stage=\"committed\", ol_discord!~\"$discord_ex\"}[$interval]) / rate(diem_consensus_block_tracing_count{job=~\"$job\", stage=\"committed\", ol_discord!~\"$discord_ex\"}[$interval])",
     "legendFormat": "id-{{job}}-id @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "Current Round per validator",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(diem_consensus_current_round)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "State Sync Committed & Synced Version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "diem_state_sync_version{type=\"committed\", job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_discord!~\"$discord_ex\"}",
     "legendFormat": "id-{{job}}-id ({{ol_node_type}}) committed @{{ol_discord}}"
    },
    {
     "expr": "diem_state_sync_version{type=\"synced\", job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_discord!~\"$discord_ex\"}",
     "legendFormat": "id-{{job}}-id ({{ol_node_type}}) synced @{{ol_discord}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RAM Used",
   "type": "timeseries",
   "description": "Non available RAM memory",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 \n- (\n    (node_memory_MemAvailable_bytes{job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_discord!~\"$discord_ex\"} * 100) / \n    node_memory_MemTotal_bytes{job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_discord!~\"$discord_ex\"}\n)",
     "legendFormat": "id-{{job}}-id {{ol_node_type}} @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job,ol_node_type,ol_discord) (rate(node_cpu_seconds_total{mode=\"idle\", job=~\"$job\", ol_node_type=~\"$ol_node_type\", ol_discord!~\"$discord_ex\"}[$interval])) * 100)",
     "legendFormat": "id-{{job}}-id {{ol_node_type}} @{{ol_discord}}"
    }
   ]
  },
  {
   "title": "WIP...",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"}",
       "legendFormat": "RAM Total {{job}} {{ol_node_type}} @{{ol_discord}}"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"} \n- node_memory_MemFree_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"} \n- (node_memory_Cached_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"} \n+ node_memory_Buffers_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"})",
       "legendFormat": "RAM Used {{job}} {{ol_node_type}} @{{ol_discord}}"
      },
      {
       "expr": "node_memory_Cached_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"} \n+ node_memory_Buffers_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"}",
       "legendFormat": "RAM Cache + Buffer {{job}} {{ol_node_type}} @{{ol_discord}}"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"}",
       "legendFormat": "RAM Free {{job}} {{ol_node_type}} @{{ol_discord}}"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"}\n - node_memory_SwapFree_bytes{job=~\"$job\",ol_node_type=~\"$ol_node_type\"})",
       "legendFormat": "SWAP Used {{job}} {{ol_node_type}} @{{ol_discord}}"
      }
     ]
    }
   ]
  }
 ]
}